
name: Python CI/CD to AWS

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    name: Deploy to AWS Lightsail
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          set -e
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          
          echo "Creating secret files..."
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          echo "${{ secrets.CREDENTIALS_JSON_CONTENT }}" > credentials.json
          echo "${{ secrets.SERVICE_JSON_CONTENT }}" > service.json
          
          echo "Starting deployment via Docker Compose..."
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          echo "Deployment complete."
